export const FETCH_USERDETAILS_REQUEST = " FETCH_USERDETAILS_REQUEST"
export const FETCH_USERDETAILS_SUCCESS = " FETCH_USERDETAILS_SUCCESS"
export const FETCH_USERDETAILS_FAILURE = " FETCH_USERDETAILS_FAILURE"